// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// Browser dev mode: mock the Go backend with sample data
const isBrowser = !window['go'];

const mockDashboard = {
  sessions: [
    { id: 'main-1', kind: 'main', isActive: true, name: 'main', messageCount: 142, lastActivity: new Date().toISOString(), totalCost: 3.47, todayCost: 1.23, model: 'claude-opus-4-6' },
    { id: 'sub-1', kind: 'subagent', isActive: false, name: 'foreprophet-agents', messageCount: 67, lastActivity: new Date(Date.now() - 3600000).toISOString(), totalCost: 1.22, todayCost: 1.22, model: 'claude-opus-4-6' },
    { id: 'sub-2', kind: 'subagent', isActive: false, name: 'foreprophet-tasks', messageCount: 89, lastActivity: new Date(Date.now() - 7200000).toISOString(), totalCost: 1.85, todayCost: 1.85, model: 'claude-opus-4-6' },
    { id: 'sub-3', kind: 'subagent', isActive: false, name: 'antenna-chart', messageCount: 34, lastActivity: new Date(Date.now() - 1800000).toISOString(), totalCost: 0.68, todayCost: 0.68, model: 'claude-opus-4-6' },
    { id: 'cron-1', kind: 'cron', isActive: true, name: 'loudhype-monitor', messageCount: 48, lastActivity: new Date(Date.now() - 900000).toISOString(), totalCost: 0.95, todayCost: 0.95, model: 'claude-opus-4-6' },
  ],
  totalCost: 8.17,
  totalMessages: 380
};

const mockHourly = Array.from({ length: 24 }, (_, i) => ({
  hour: new Date(Date.now() - (23 - i) * 3600000).toISOString(),
  messages: Math.floor(Math.random() * 20) + (i > 8 && i < 22 ? 10 : 1),
  cost: parseFloat((Math.random() * 0.5 + (i > 8 && i < 22 ? 0.2 : 0.01)).toFixed(3))
}));

export function GetDashboard() {
  if (isBrowser) return Promise.resolve(mockDashboard);
  return window['go']['main']['App']['GetDashboard']();
}

export function GetHourlyActivity() {
  if (isBrowser) return Promise.resolve(mockHourly);
  return window['go']['main']['App']['GetHourlyActivity']();
}
