// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

const isBrowser = !window['go'];

export function GetDashboard() {
  if (isBrowser) return fetch('/api/dashboard').then(r => r.json());
  return window['go']['main']['App']['GetDashboard']();
}

export function GetHourlyActivity() {
  if (isBrowser) return fetch('/api/hourly').then(r => r.json());
  return window['go']['main']['App']['GetHourlyActivity']();
}
